package com.pirxhio.affirmity.auth

import android.content.Context
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialException
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential

/**
 * Resolves the `default_web_client_id` string resource generated by the `google-services`
 * plugin by name, at runtime. Returns `null` (never crashes) when the resource is absent or
 * blank — e.g. the console has no web OAuth client yet.
 */
internal fun webClientId(context: Context): String? =
    context.resources
        .getIdentifier("default_web_client_id", "string", context.packageName)
        .takeIf { it != 0 }
        ?.let(context::getString)
        ?.takeIf { it.isNotBlank() }

/**
 * Maps a Credential Manager failure `type`/`message` onto [AuthError]. Pure — no Firebase/Android
 * dependency — so every branch is unit-testable. `null` means user cancellation: not an error.
 */
internal fun classifyCredentialError(type: String, message: String?): AuthError? = when {
    type.contains("CANCELED", ignoreCase = true) || type.contains("CANCELLED", ignoreCase = true) -> null
    type.contains("NO_CREDENTIAL", ignoreCase = true) -> AuthError.NoCredentialAvailable
    type.contains("PROVIDER_CONFIGURATION", ignoreCase = true) ||
        message?.contains("Play Services", ignoreCase = true) == true -> AuthError.ProviderUnavailable
    else -> AuthError.Unknown(message)
}

/** Thrown to carry a classified [AuthError] through a [Result.failure]. */
internal class AuthException(val error: AuthError) : Exception(error.toString())

/** Thrown to carry a cancelled sign-in (not an error) through a [Result.failure]. */
internal class SignInCancelledException : Exception()

/**
 * [AuthProvider] for Google, backed by Android Credential Manager + Google ID
 * (never the deprecated `GoogleSignInClient`).
 */
class GoogleIdAuthProvider(
    private val credentialManager: CredentialManager,
) : AuthProvider {
    override val id: AuthProviderId = AuthProviderId.GOOGLE

    override suspend fun requestCredential(activityContext: Context): Result<ProviderCredential> {
        val clientId = webClientId(activityContext)
            ?: return Result.failure(AuthException(AuthError.ConfigurationMissing))

        // Try previously-authorized accounts first (silent, returning-user path). Google accounts
        // that exist on the device but never signed into this app don't count as "authorized," so a
        // first-time sign-in always fails this pass with NoCredentialAvailable even when the device
        // has Google accounts — that failure alone doesn't mean sign-in is impossible, only that we
        // must fall back to the full account picker.
        val silentAttempt = signIn(activityContext, clientId, filterByAuthorizedAccounts = true)
        val isFirstTimeUser = silentAttempt.exceptionOrNull()
            .let { it is AuthException && it.error == AuthError.NoCredentialAvailable }
        if (!isFirstTimeUser) return silentAttempt

        return signIn(activityContext, clientId, filterByAuthorizedAccounts = false)
    }

    private suspend fun signIn(
        activityContext: Context,
        clientId: String,
        filterByAuthorizedAccounts: Boolean,
    ): Result<ProviderCredential> {
        val request = GetCredentialRequest.Builder()
            .addCredentialOption(
                GetGoogleIdOption.Builder()
                    .setFilterByAuthorizedAccounts(filterByAuthorizedAccounts)
                    .setServerClientId(clientId)
                    .build(),
            )
            .build()

        return try {
            val response = credentialManager.getCredential(activityContext, request)
            val credential = response.credential
            if (credential is CustomCredential &&
                credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
            ) {
                val idTokenCredential = GoogleIdTokenCredential.createFrom(credential.data)
                Result.success(ProviderCredential.IdToken(providerId = "google.com", token = idTokenCredential.idToken))
            } else {
                Result.failure(AuthException(AuthError.Unknown("Unexpected credential type")))
            }
        } catch (e: GetCredentialException) {
            when (val classified = classifyCredentialError(e.type, e.message)) {
                null -> Result.failure(SignInCancelledException())
                else -> Result.failure(AuthException(classified))
            }
        }
    }
}
