package com.pirxhio.affirmity.ui.groups

import com.pirxhio.affirmity.R

/** Compile-time map from theme id to its localized label resource (no reflection, R8-safe).
 *  Guarded by `CatalogThemeTitlesTest`, which checks it covers every theme in [catalogThemes]. */
val catalogThemeTitleRes: Map<String, Int> = mapOf(
    "body_energy_wellbeing.body_acceptance" to R.string.catalog_theme_body_energy_wellbeing_body_acceptance,
    "body_energy_wellbeing.body_care" to R.string.catalog_theme_body_energy_wellbeing_body_care,
    "body_energy_wellbeing.body_confidence" to R.string.catalog_theme_body_energy_wellbeing_body_confidence,
    "body_energy_wellbeing.energy" to R.string.catalog_theme_body_energy_wellbeing_energy,
    "body_energy_wellbeing.enjoy_movement" to R.string.catalog_theme_body_energy_wellbeing_enjoy_movement,
    "body_energy_wellbeing.physical_capability" to R.string.catalog_theme_body_energy_wellbeing_physical_capability,
    "calm_peace.find_calm" to R.string.catalog_theme_calm_peace_find_calm,
    "calm_peace.overwhelmed" to R.string.catalog_theme_calm_peace_overwhelmed,
    "calm_peace.release_tension" to R.string.catalog_theme_calm_peace_release_tension,
    "calm_peace.rest_without_guilt" to R.string.catalog_theme_calm_peace_rest_without_guilt,
    "change_loss_new_beginnings.adapt_to_change" to R.string.catalog_theme_change_loss_new_beginnings_adapt_to_change,
    "change_loss_new_beginnings.closure" to R.string.catalog_theme_change_loss_new_beginnings_closure,
    "change_loss_new_beginnings.difficult_period" to R.string.catalog_theme_change_loss_new_beginnings_difficult_period,
    "change_loss_new_beginnings.grief" to R.string.catalog_theme_change_loss_new_beginnings_grief,
    "change_loss_new_beginnings.new_beginning" to R.string.catalog_theme_change_loss_new_beginnings_new_beginning,
    "change_loss_new_beginnings.rebuild" to R.string.catalog_theme_change_loss_new_beginnings_rebuild,
    "confidence_courage.believe_in_my_abilities" to R.string.catalog_theme_confidence_courage_believe_in_my_abilities,
    "confidence_courage.decisions" to R.string.catalog_theme_confidence_courage_decisions,
    "confidence_courage.failure" to R.string.catalog_theme_confidence_courage_failure,
    "confidence_courage.impostor" to R.string.catalog_theme_confidence_courage_impostor,
    "confidence_courage.move_with_fear" to R.string.catalog_theme_confidence_courage_move_with_fear,
    "confidence_courage.take_space" to R.string.catalog_theme_confidence_courage_take_space,
    "connection_belonging.authentic_connection" to R.string.catalog_theme_connection_belonging_authentic_connection,
    "connection_belonging.belonging" to R.string.catalog_theme_connection_belonging_belonging,
    "connection_belonging.find_my_people" to R.string.catalog_theme_connection_belonging_find_my_people,
    "connection_belonging.friendships" to R.string.catalog_theme_connection_belonging_friendships,
    "connection_belonging.loneliness" to R.string.catalog_theme_connection_belonging_loneliness,
    "connection_belonging.own_company" to R.string.catalog_theme_connection_belonging_own_company,
    "expectations_boundaries_freedom.boundaries" to R.string.catalog_theme_expectations_boundaries_freedom_boundaries,
    "expectations_boundaries_freedom.external_expectations" to R.string.catalog_theme_expectations_boundaries_freedom_external_expectations,
    "expectations_boundaries_freedom.life_timeline" to R.string.catalog_theme_expectations_boundaries_freedom_life_timeline,
    "expectations_boundaries_freedom.perfectionism" to R.string.catalog_theme_expectations_boundaries_freedom_perfectionism,
    "expectations_boundaries_freedom.self_pressure" to R.string.catalog_theme_expectations_boundaries_freedom_self_pressure,
    "gratitude_hope_possibility.gratitude" to R.string.catalog_theme_gratitude_hope_possibility_gratitude,
    "gratitude_hope_possibility.hope" to R.string.catalog_theme_gratitude_hope_possibility_hope,
    "gratitude_hope_possibility.possibilities" to R.string.catalog_theme_gratitude_hope_possibility_possibilities,
    "love_desire_romantic_relationships.breakup_recovery" to R.string.catalog_theme_love_desire_romantic_relationships_breakup_recovery,
    "love_desire_romantic_relationships.desire_attraction" to R.string.catalog_theme_love_desire_romantic_relationships_desire_attraction,
    "love_desire_romantic_relationships.intimacy" to R.string.catalog_theme_love_desire_romantic_relationships_intimacy,
    "love_desire_romantic_relationships.receive_love" to R.string.catalog_theme_love_desire_romantic_relationships_receive_love,
    "love_desire_romantic_relationships.rejection" to R.string.catalog_theme_love_desire_romantic_relationships_rejection,
    "love_desire_romantic_relationships.secure_relationship" to R.string.catalog_theme_love_desire_romantic_relationships_secure_relationship,
    "mind_anxiety.catastrophizing" to R.string.catalog_theme_mind_anxiety_catastrophizing,
    "mind_anxiety.intrusive_thoughts" to R.string.catalog_theme_mind_anxiety_intrusive_thoughts,
    "mind_anxiety.negative_thoughts" to R.string.catalog_theme_mind_anxiety_negative_thoughts,
    "mind_anxiety.overthinking" to R.string.catalog_theme_mind_anxiety_overthinking,
    "mind_anxiety.social_judgment" to R.string.catalog_theme_mind_anxiety_social_judgment,
    "motivation_discipline_responsibility.act_without_motivation" to R.string.catalog_theme_motivation_discipline_responsibility_act_without_motivation,
    "motivation_discipline_responsibility.discipline_consistency" to R.string.catalog_theme_motivation_discipline_responsibility_discipline_consistency,
    "motivation_discipline_responsibility.finish_what_i_start" to R.string.catalog_theme_motivation_discipline_responsibility_finish_what_i_start,
    "motivation_discipline_responsibility.personal_accountability" to R.string.catalog_theme_motivation_discipline_responsibility_personal_accountability,
    "motivation_discipline_responsibility.procrastination" to R.string.catalog_theme_motivation_discipline_responsibility_procrastination,
    "motivation_discipline_responsibility.return_after_quitting" to R.string.catalog_theme_motivation_discipline_responsibility_return_after_quitting,
    "presence_acceptance_control.personal_agency" to R.string.catalog_theme_presence_acceptance_control_personal_agency,
    "presence_acceptance_control.present_moment" to R.string.catalog_theme_presence_acceptance_control_present_moment,
    "presence_acceptance_control.reality_acceptance" to R.string.catalog_theme_presence_acceptance_control_reality_acceptance,
    "presence_acceptance_control.release_uncontrollable" to R.string.catalog_theme_presence_acceptance_control_release_uncontrollable,
    "presence_acceptance_control.uncertainty" to R.string.catalog_theme_presence_acceptance_control_uncertainty,
    "purpose_identity_direction.direction" to R.string.catalog_theme_purpose_identity_direction_direction,
    "purpose_identity_direction.identity_growth" to R.string.catalog_theme_purpose_identity_direction_identity_growth,
    "purpose_identity_direction.purpose" to R.string.catalog_theme_purpose_identity_direction_purpose,
    "purpose_identity_direction.self_discovery" to R.string.catalog_theme_purpose_identity_direction_self_discovery,
    "purpose_identity_direction.trust_process" to R.string.catalog_theme_purpose_identity_direction_trust_process,
    "purpose_identity_direction.values" to R.string.catalog_theme_purpose_identity_direction_values,
    "self_worth.achievement_recognition" to R.string.catalog_theme_self_worth_achievement_recognition,
    "self_worth.comparison" to R.string.catalog_theme_self_worth_comparison,
    "self_worth.feeling_enough" to R.string.catalog_theme_self_worth_feeling_enough,
    "self_worth.inner_dialogue" to R.string.catalog_theme_self_worth_inner_dialogue,
    "self_worth.recognize_my_value" to R.string.catalog_theme_self_worth_recognize_my_value,
    "self_worth.self_forgiveness" to R.string.catalog_theme_self_worth_self_forgiveness,
    "work_money_growth.career_growth" to R.string.catalog_theme_work_money_growth_career_growth,
    "work_money_growth.entrepreneurship" to R.string.catalog_theme_work_money_growth_entrepreneurship,
    "work_money_growth.money_relationship" to R.string.catalog_theme_work_money_growth_money_relationship,
    "work_money_growth.work_value_compensation" to R.string.catalog_theme_work_money_growth_work_value_compensation,
)
